project:
  type: website

website:
  title: "Machine Learning Clearly Explained"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: regression.qmd
        text: Regression
      - href: classification.qmd
        text: Classification
      - href: clustering.qmd
        text: Clustering
      - about.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

