project:
  type: website

website:
  title: "Machine Learning Clearly Explained"
  navbar:
    left:
      - href: index.qmd
        text: Regression
      - href: classification.qmd
        text: Classification
      - href: clustering.qmd
        text: Clustering
      - about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

