---
title: "Introduction"
---

Machine learning is one of the most important developments in computer science. It has driven modern progress in many ways, improving medical research, construction methods, urban planning, and most any field that you can name that generates and consumes data.

Fundamentally, **it is a way for computers to learn from data and improve at tasks without being explicitly told what to do step by step.**

Instead of writing rules by hand, we give the computer a lot of examples, and it figures out patterns or rules on its own.

For example:

If you want a computer to recognize pictures of cats, instead of coding all the features of a cat (like fur, ears, tail...), you show it many labeled pictures of cats and non-cats.

Over time, it "learns" what features make a cat picture likely, based on those examples.

But that is not all. It depends on what models you utilize, but a computer doesn't even need labels to recognize patterns in your data.

If you want a computer to tell you what marketing might work best, then you can give it the data from several customers. This is very common in today's society and used in almost every industry.

Over time, the computer "learns" what features are distinct from customer to customer and labels the customer by what marketing could work best and result in higher sales.

Both of these instances are kind of like teaching by example rather than instruction.
